### PR TITLE
suggestion for throttling_disabled

### PR DESCRIPTION
**Pull request by tlambert03**
hey @Czaki  ... this would have been my preference for the `throttling_disabled` context manager (more specific to an object, harder to abuse... doesn't require patching the class ... etc).  let me know what you think

### CODE REVIEW

**Comment by Czaki** [comment]
How will you use it in napari test? 

As I understand, There will be a need to handle references to every `GenericSignalThrottler`. So this util cannot be used to test functions decorated by `qdebounced` or `qthrottled`?

And put additional responsibility on reviewers to ensure that when adding new throttle to disable it in tests.

**Comment by tlambert03** [comment]
> So this util cannot be used to test functions decorated by qdebounced or qthrottled?

Not sure I'm following, The included test literally tests exactly that.

Can you maybe give me an example of what you can't do with this in your napari tests?

> And put additional responsibility on reviewers to ensure that when adding new throttle to disable it in tests.

You could say that, or you could say "avoids global magic changes and opts for explicit blocking"

**Comment by Czaki** [comment]
How this solution could be used to test such code? Without need to wait 1500ms.

```python 

class SomeWidget(QWidget):
	def __init__(self, viewer):
		...
		viewer.events.cursor.connect(qdebounced(self.heavy_function, timeout=1500))
		
	def heavy_function(self):
		"""some heavy calculation depends on cursor position"""
```

**Comment by tlambert03** [comment]
you could either save a reference to `func = qdebounced(self.heavy_function, timeout=1500)` before connecting or loop through the callbacks connected to `viewer.events.cursor` and disable_throttling on them ...

if you don't like that, i do really think this might just be a good case for doing your own thing in napari tests.

**Comment by Czaki** [comment]
`GenericSignalThrottler` is not a part of the public API. So there is no guarantee that it will be accesible under same path.

I will ask other core devs what they prefer.

**Comment by tlambert03** [comment]
Yeah, but the "cost" of that is minuscule!  One pr and your tests are fixed, no users harmed.  Work with me here ...

**Pull request closed without merging**
